---
local:
  root_dir : <%= ENV['GITHUB_WORKSPACE'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "snowplow-generic"
    name     : "sql-runner"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= ENV['SQL_RUNNER_VERSION'] %>
    build_version : <%= ENV['TAG_VERSION'] %>
    artifacts:
      - prefix : "sql_runner_"
        suffix : "_linux_amd64"
        type   : "zip"
        binary_paths:
          - build/output/linux/sql-runner
      - prefix : "sql_runner_"
        suffix : "_darwin_amd64"
        type   : "zip"
        binary_paths:
          - build/output/darwin/sql-runner
      - prefix : "sql_runner_"
        suffix : "_windows_amd64"
        type   : "zip"
        binary_paths:
          - build/output/windows/sql-runner.exe
