name: Deploy

on:
  push:
    tags:
    - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Launch the docker-compose stack
      run: make setup-up

    - name: Build
      run: make

    - name: Test and send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make
        make goveralls
        DISTRO=linux make integration

    - name: Get tag and sql-runner version information
      id: version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/*/}
        echo "##[set-output name=SQL_RUNNER_VERSION;]$(cat VERSION)"

    - name: Fail if version mismatch
      if: ${{ steps.version.outputs.TAG_VERSION != steps.version.outputs.SQL_RUNNER_VERSION }}
      run: |
        echo "Tag version (${{ steps.version.outputs.TAG_VERSION }}) doesn't match version in project (${{ steps.version.outputs.SQL_RUNNER_VERSION }})"
        exit 1

    - name: Make release assets
      run: make release

    - name: Get date for release name
      id: date
      run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Version ${{ github.ref }} (${{ env.RELEASE_DATE }})
        draft: false
        prerelease: ${{ contains(steps.version.outputs.TAG_VERSION, '-rc') }}

    - name: Upload release assets
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./build/dist/*"]'
